gpu_num: 2
add_note: MVSA-multiple-bert-r50-64
lr: 2.0e-5
fuse_lr: 2.0e-5
image_output_type: all
optim: adamw
data_type: MVSA-multiple
train_fuse_model_epoch: 20
epoch : 30
warmup_step_epoch: 2
image_model: resnet-50
text_model: bert-base
fuse_type: att
batch: 64
acc_grad: 1
tran_num_layers: 4
image_num_layers: 2
fixed_image_model: True
